/**
 * Hub categories — sidebar links + lazy homepage rows (GamePix slugs)
 */
window.VIXO_CATEGORIES = [
  { slug: "multiplayer", title: "Multiplayer", desc: "Play online with others" },
  { slug: "battle", title: "Action", desc: "Combat and adventure" },
  { slug: "arcade", title: "Arcade", desc: "Quick classics and high scores" },
  { slug: "match-3", title: "Puzzle", desc: "Match, think and solve" },
  { slug: "racing", title: "Racing", desc: "Cars, speed and driving" },
  { slug: "sports", title: "Sports", desc: "Ball games and athletics" },
  { slug: "adventure", title: "Adventure", desc: "Explore and quest" },
  { slug: "shooting", title: "Shooting", desc: "Aim and fire" },
  { slug: "strategy", title: "Strategy", desc: "Plan and conquer" },
  { slug: "simulation", title: "Simulation", desc: "Sim games and management" },
  { slug: "platform", title: "Platform", desc: "Jump and run" },
  { slug: "skill", title: "Skill", desc: "Timing and reflexes" },
  { slug: "casual", title: "Casual", desc: "Easy fun for everyone" },
  { slug: "kids", title: "Kids", desc: "Family-friendly games" },
  { slug: "girls", title: "Girls", desc: "Fashion and creativity" },
  { slug: "boys", title: "Boys", desc: "Action-packed picks" },
  { slug: "clicker", title: "Clicker", desc: "Tap and upgrade" },
  { slug: "idle", title: "Idle", desc: "Progress while you wait" },
  { slug: "io", title: ".io", desc: "Browser arena games" },
  { slug: "tower-defense", title: "Tower Defense", desc: "Defend your base" },
  { slug: "zombie", title: "Zombie", desc: "Survive the undead" },
  { slug: "war", title: "War", desc: "Military and battle" },
  { slug: "stickman", title: "Stickman", desc: "Stick figure action" },
  { slug: "snake", title: "Snake", desc: "Classic snake games" },
  { slug: "puzzle", title: "Brain", desc: "Logic and brain teasers" },
  { slug: "card", title: "Card", desc: "Cards and solitaire" },
  { slug: "board", title: "Board", desc: "Board and tabletop" },
  { slug: "mahjong", title: "Mahjong", desc: "Tile matching" },
  { slug: "word", title: "Word", desc: "Letters and vocabulary" },
  { slug: "cooking", title: "Cooking", desc: "Kitchen and recipes" },
  { slug: "dress-up", title: "Dress Up", desc: "Style and outfits" },
  { slug: "beauty", title: "Beauty", desc: "Makeover and spa" },
  { slug: "princess", title: "Princess", desc: "Royal adventures" },
  { slug: "football", title: "Football", desc: "Soccer and goals" },
  { slug: "basketball", title: "Basketball", desc: "Hoops and dunks" },
  { slug: "golf", title: "Golf", desc: "Courses and swings" },
  { slug: "tennis", title: "Tennis", desc: "Courts and rallies" },
  { slug: "baseball", title: "Baseball", desc: "Bats and home runs" },
  { slug: "boxing", title: "Fighting", desc: "Boxing and MMA" },
  { slug: "driving", title: "Driving", desc: "Steer and cruise" },
  { slug: "parking", title: "Parking", desc: "Park without crashing" },
  { slug: "motocross", title: "Motocross", desc: "Bikes and dirt tracks" },
  { slug: "car", title: "Car", desc: "Cars and garages" },
  { slug: "truck", title: "Truck", desc: "Big rigs and cargo" },
  { slug: "airplane", title: "Flying", desc: "Planes and sky" },
  { slug: "boat", title: "Boat", desc: "Sailing and water" },
  { slug: "fishing", title: "Fishing", desc: "Catch and relax" },
  { slug: "hunting", title: "Hunting", desc: "Aim in the wild" },
  { slug: "escape", title: "Escape", desc: "Room escape puzzles" },
  { slug: "hidden-object", title: "Hidden Object", desc: "Find every item" },
  { slug: "bubble", title: "Bubble", desc: "Pop and match bubbles" },
  { slug: "tetris", title: "Tetris", desc: "Stack the blocks" },
  { slug: "minecraft", title: "Minecraft", desc: "Block worlds" },
  { slug: "horror", title: "Horror", desc: "Scary thrills" },
  { slug: "funny", title: "Funny", desc: "Laugh-out-loud fun" },
  { slug: "music", title: "Music", desc: "Rhythm and sound" },
  { slug: "educational", title: "Educational", desc: "Learn while playing" },
  { slug: "math", title: "Math", desc: "Numbers and puzzles" },
  { slug: "farm", title: "Farm", desc: "Grow and harvest" },
  { slug: "restaurant", title: "Restaurant", desc: "Serve customers fast" },
  { slug: "hospital", title: "Hospital", desc: "Care and heal" },
  { slug: "pet", title: "Pets", desc: "Animals and care" },
  { slug: "dinosaur", title: "Dinosaur", desc: "Prehistoric fun" },
  { slug: "space", title: "Space", desc: "Stars and galaxies" },
  { slug: "pirate", title: "Pirate", desc: "Treasure and ships" },
  { slug: "ninja", title: "Ninja", desc: "Stealth and swords" },
  { slug: "archery", title: "Archery", desc: "Bows and targets" },
  { slug: "sniper", title: "Sniper", desc: "Long-range shots" },
  { slug: "rpg", title: "RPG", desc: "Role-playing quests" },
  { slug: "mmo", title: "MMO", desc: "Massive online worlds" },
  { slug: "two-player", title: "2 Player", desc: "Play on one screen" },
  { slug: "co-op", title: "Co-op", desc: "Team up together" },
];
